//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employement
    {
        public int id { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
        public Nullable<double> HourSpent { get; set; }
        public string Description { get; set; }
        public int id_Employee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
